import Link from "next/link";
import { AlertTriangle } from "lucide-react";

export function UnknownVersionView({ version }: { version: string }) {
  return (
    <div className="no-params-center anim-fade-up">
      <div className="no-params-icon">
        <AlertTriangle size={20} color="#9090a8" strokeWidth={1.5} />
      </div>
      <h1 className="no-params-title">Unsupported link version</h1>
      <p className="no-params-body">
        This link uses{" "}
        <code className="inline-code">v={version}</code>, which is not
        supported by this version of the site. The link may have been
        generated by a newer version of the Worktree runner. Please update
        your runner to open this workspace.
      </p>
      <Link href="/" className="btn-ghost">
        ← Back to home
      </Link>
    </div>
  );
}
